/** Public relations whose rows are owned by a User and therefore require forced RLS. */
export const userTableNames = [
  "agent_confirmation_consumptions",
  "audit_log_entries",
  "backup_recovery_credentials",
  "budget_month_latches",
  "budgets",
  "compacted_conversations",
  "consent_records",
  "conversation_continuity",
  "conversation_turns",
  "dashboards",
  "hosted_agent_sessions",
  "insight_delivery_attempts",
  "insight_events",
  "insight_money_groups",
  "keyword_rules",
  "memories",
  "memory_revisions",
  "needs_review_items",
  "source_attestations",
  "statement_backfill_entitlements",
  "statement_format_profiles",
  "statement_submissions",
  "tokens",
  "transactions",
  "transcript_entries",
  "users",
  "verified_email_credentials",
  "whatsapp_conversation_windows",
  "whatsapp_identities",
  "whatsapp_identity_change_evidence",
  "whatsapp_inbound_jobs",
  "whatsapp_message_evidence",
  "whatsapp_turn_claims",
] as const;
