import { Effect, FileSystem, Path } from "effect";
import { EmailCatalogGenerationFailed } from "~/shell/ingestion/contract";

const discoverFormats = Effect.fn(function* (root: string) {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;
  const entries = yield* fs.readDirectory(root);
  const paths: Array<string> = [];
  for (const entry of entries) {
    const directory = path.join(root, entry);
    if ((yield* fs.stat(directory)).type !== "Directory") continue;
    if (!(yield* fs.exists(path.join(directory, "format.ts")))) continue;
    if (!(yield* fs.exists(path.join(directory, "fixtures", "positive.synthetic.html")))) {
      return yield* new EmailCatalogGenerationFailed({ reason: "missing-fixture" });
    }
    paths.push(`${entry}/format.ts`);
  }
  if (paths.length === 0) {
    return yield* new EmailCatalogGenerationFailed({ reason: "missing-formats" });
  }
  return paths.sort((left, right) => left.localeCompare(right));
});

const catalogSource = (paths: ReadonlyArray<string>): string => {
  const imports = paths
    .map(
      (path, index) =>
        `import { format as format${index} } from "~/shell/ingestion/internal/email-interpretation/formats/${path.replace(/\.ts$/u, "")}";`
    )
    .join("\n");
  const names = paths.map((_, index) => `format${index}`).join(", ");
  return `/* Generated by tools/email-formats/generate-runtime.ts. Do not edit. */
import type { NotificationEmailFormat } from "./format-definition";
${imports}

export const generatedFormats: ReadonlyArray<NotificationEmailFormat> = [${names}];
`;
};

/** Regenerate or verify the owner-private deterministic catalog; never return catalog contents. */
export const generateNotificationEmailCatalog = Effect.fn(function* (check: boolean) {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;
  const formatsRoot = yield* path.fromFileUrl(new URL("./formats", import.meta.url));
  const output = yield* path.fromFileUrl(new URL("./catalog.generated.ts", import.meta.url));
  const content = catalogSource(yield* discoverFormats(formatsRoot));
  if (check) {
    const current = (yield* fs.exists(output)) ? yield* fs.readFileString(output) : "";
    if (current !== content) {
      return yield* new EmailCatalogGenerationFailed({ reason: "stale-catalog" });
    }
  } else {
    yield* fs.writeFileString(output, content);
  }
});
