import { Schema } from "effect";
import { UtcTimestamp } from "~/core/_shared/time";
import { maximumStatementBytes } from "./model";

export { maximumStatementBytes };

const hoursPerDay = 24;
const minutesPerHour = 60;
const secondsPerMinute = 60;
const millisecondsPerSecond = 1000;
const maximumSweepRows = 200;

/**
 * How long unpublished staged statement bytes stay readable. Expiry is a hard bound, not a
 * retention preference: an expired staging row is neither publishable nor readable, and the
 * bounded sweep may delete its R2 object at any point after it.
 */
export const statementStagingLifetimeMilliseconds =
  hoursPerDay * minutesPerHour * secondsPerMinute * millisecondsPerSecond;

/** Largest number of expired staging rows one cleanup sweep will act on. */
export const maximumStatementStagingSweep = maximumSweepRows;

/**
 * Opaque, unpredictable identity of one staged statement object. It is generated by the server
 * from cryptographic entropy and never derived from a UserId, filename, digest, or byte count, so
 * possessing it proves nothing about ownership and another User's reference cannot be guessed.
 */
export const StatementStagingId = Schema.String.check(Schema.isUUID())
  .pipe(Schema.brand("StatementStagingId"))
  .annotate({ identifier: "StatementStagingId" });
export type StatementStagingId = typeof StatementStagingId.Type;

/** Lowercase hexadecimal SHA-256 digest of the exact staged bytes. Not a secret. */
export const StatementContentDigest = Schema.String.check(Schema.isPattern(/^[0-9a-f]{64}$/u))
  .pipe(Schema.brand("StatementContentDigest"))
  .annotate({ identifier: "StatementContentDigest" });
export type StatementContentDigest = typeof StatementContentDigest.Type;

/**
 * Non-authoritative acknowledgement of one staged object: identity, the actual received byte
 * length, the digest of those bytes, and the server-owned expiry. It is not a StatementSubmission
 * and confers no eligibility for extraction; only D1 publication creates authority.
 */
export const StagedStatementBytes = Schema.Struct({
  stagingId: StatementStagingId,
  byteLength: Schema.Int.check(Schema.isBetween({ minimum: 1, maximum: maximumStatementBytes })),
  sha256: StatementContentDigest,
  expiresAt: UtcTimestamp,
}).annotate({ identifier: "StagedStatementBytes" });
export type StagedStatementBytes = typeof StagedStatementBytes.Type;

/**
 * Bounded caller-held handle to staged bytes, as it will appear inside a canonical submission
 * input. Every field is verified against the stored staging row and the private R2 object before
 * any authoritative D1 state commits; a caller can neither shorten it nor point it at another
 * User's material.
 */
export const StagedStatementReference = Schema.Struct({
  stagingId: StatementStagingId,
  byteLength: Schema.Int.check(Schema.isBetween({ minimum: 1, maximum: maximumStatementBytes })),
  sha256: StatementContentDigest,
}).annotate({ identifier: "StagedStatementReference" });
export type StagedStatementReference = typeof StagedStatementReference.Type;

/**
 * Closed staging refusal vocabulary. Reasons are safe to map to canonical failures: none contains
 * statement contents, a filename, a digest, or platform detail. `cancelled` means the caller's own
 * request ended before the bytes were complete.
 */
export const StatementStagingFailureReason = Schema.Literals([
  "resource-limit",
  "malformed-file",
  "cancelled",
  "retention-expired",
  "not-found",
  "conflict",
]);
export type StatementStagingFailureReason = typeof StatementStagingFailureReason.Type;
