import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const serverRoot = dirname(dirname(dirname(fileURLToPath(import.meta.url))));
const formatsRoot = join(serverRoot, "src/shell/ingestion/email-interpretation/formats");
const output = join(serverRoot, "src/shell/ingestion/email-interpretation/catalog.generated.ts");
const check = process.argv.includes("--check");

const paths = readdirSync(formatsRoot, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => join(formatsRoot, entry.name, "format.ts"))
  .filter(existsSync)
  .map((path) => relative(formatsRoot, path).replaceAll("\\", "/"))
  .sort((left, right) => left.localeCompare(right));
if (paths.length === 0) {
  throw new Error("No notification-email formats were discovered");
}
for (const path of paths) {
  const fixture = join(formatsRoot, dirname(path), "fixtures", "positive.synthetic.html");
  if (!existsSync(fixture)) {
    throw new Error(`Notification-email format is missing its positive synthetic fixture: ${path}`);
  }
}

const imports = paths
  .map(
    (path, index) =>
      `import { format as format${index} } from "~/shell/ingestion/email-interpretation/formats/${path.replace(/\.ts$/u, "")}";`
  )
  .join("\n");
const names = paths.map((_, index) => `format${index}`).join(", ");
const content = `/* Generated by tools/email-formats/generate.ts. Do not edit. */
import type { NotificationEmailFormat } from "./format-definition";
${imports}

export const generatedFormats: ReadonlyArray<NotificationEmailFormat> = [${names}];
`;

if (check) {
  const current = existsSync(output) ? readFileSync(output, "utf8") : "";
  if (current !== content) {
    throw new Error("Generated notification-email catalog is stale. Run email-formats:generate.");
  }
} else {
  writeFileSync(output, content);
}
