/** Latest successful CI durations used when no generated timing cache is available. */
export const serverTestTimings = {
  "src/shell/email-authentication/authentication.test.ts": 95.053,
  "src/shell/channels/whatsapp/whatsapp-channel.test.ts": 68.277,
  "src/shell/email-authentication/replacement-workflow.integration.test.ts": 51.14,
  "src/shell/email-authentication/pairing-workflow.integration.test.ts": 45.922,
  "src/shell/agent/hosted-turns.integration.test.ts": 29.84,
  "src/shell/onboarding/delivery-workflow.integration.test.ts": 17.144,
  "src/shell/onboarding/onboarding.test.ts": 17.054,
  "src/shell/agent/agent-service.test.ts": 15.838,
  "src/shell/cluster-topology.integration.test.ts": 14.613,
  "src/shell/channels/whatsapp/disclosure-workflow.integration.test.ts": 12.52,
  "src/shell/ingestion/forwarded-email-workflow.integration.test.ts": 10.79,
  "src/shell/dashboard/handlers.test.ts": 9.783,
  "src/shell/transactions/handlers.test.ts": 9.765,
  "src/shell/testing/isolation.test.ts": 8.501,
  "src/shell/transcript/conversation-continuity.test.ts": 8.208,
  "src/shell/ingestion/worker.test.ts": 7.998,
  "src/shell/subscription/billing-reconciliation.integration.test.ts": 7.423,
  "src/shell/durable-queue-health.test.ts": 5.607,
  "src/shell/db/migrations/0028-persisted-schema-reconciliation.test.ts": 5.134,
  "src/shell/ingestion/email-forwarding.test.ts": 4.963,
  "src/shell/testing/suggested-operations.test.ts": 3.871,
  "src/shell/email-authentication/replacement.test.ts": 3.054,
  "src/shell/browser-login/handlers.test.ts": 3.002,
  "src/shell/channels/whatsapp/disclosure-retention.test.ts": 2.876,
  "src/shell/channels/whatsapp/disclosure-races.test.ts": 2.771,
  "src/shell/channels/whatsapp/disclosure-delivery.test.ts": 2.716,
  "src/shell/ingestion/forwarded-email-recovery.test.ts": 2.162,
  "src/shell/tokens/distributed-admission.test.ts": 2.063,
};
