-- The mailbox token is generated by the authenticated canonical enableEmailForwarding operation.
-- A mailbox address, message header and object key never establish User authority by themselves.
CREATE TABLE email_forwarding_addresses (
  id TEXT NOT NULL UNIQUE CHECK (length(id) = 36),
  user_id TEXT PRIMARY KEY NOT NULL REFERENCES users(id),
  local_part TEXT NOT NULL UNIQUE CHECK (length(local_part) BETWEEN 24 AND 64),
  created_at_ms INTEGER NOT NULL
) STRICT;

-- One identity for one exact bounded raw delivery at one approved recipient. The receipt is
-- reserved before R2, and the durable outbox is published only after R2 acknowledges the bytes.
-- Issuance happens only after verified onboarding commits its stable-User Consent evidence.
-- The random token is not derived from a mailbox, phone, or provider identifier.
CREATE TRIGGER issue_forwarding_address AFTER INSERT ON onboarding_consent_records
BEGIN
  INSERT INTO email_forwarding_addresses (id, user_id, local_part, created_at_ms)
  VALUES (
    lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||
    substr(lower(hex(randomblob(2))), 2, 3) || '-8' ||
    substr(lower(hex(randomblob(2))), 2, 3) || '-' || lower(hex(randomblob(6))),
    NEW.user_id, lower(hex(randomblob(24))), NEW.accepted_at_ms
  );
END;

-- Existing verified Users must be able to obtain the same address as newly onboarded Users.
-- Issuance precedes any Email Worker admission and is once-only for each User.
INSERT INTO email_forwarding_addresses (id, user_id, local_part, created_at_ms)
SELECT lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||
  substr(lower(hex(randomblob(2))), 2, 3) || '-8' ||
  substr(lower(hex(randomblob(2))), 2, 3) || '-' || lower(hex(randomblob(6))),
  c.user_id, lower(hex(randomblob(24))), c.accepted_at_ms
FROM onboarding_consent_records c
WHERE NOT EXISTS (SELECT 1 FROM consent_user_revocations r WHERE r.user_id = c.user_id);

-- Extend the existing canonical ingestion Audit table, which already participates in every
-- shared daily-work budget trigger. Keep all prior evidence and its append-only policy.
-- The four older canonical budget triggers reference this Audit table by name; remove
-- them before rebuilding it so SQLite can drop the old table, then restore them below.
DROP TRIGGER transaction_audit_daily_budget;
DROP TRIGGER pat_canonical_daily_budget;
DROP TRIGGER category_canonical_daily_budget;
DROP TRIGGER memory_canonical_daily_budget;
DROP TRIGGER statement_submission_audit_no_update;
DROP TRIGGER statement_submission_audit_no_delete;
DROP TRIGGER statement_audit_daily_budget;
CREATE TABLE statement_submission_audit_next (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL REFERENCES users(id),
  operation TEXT NOT NULL CHECK (operation IN ('ingestion.submitForExtraction',
    'ingestion.getStatementSubmission', 'ingestion.enableEmailForwarding',
    'ingestion.getEmailForwarding')),
  outcome TEXT NOT NULL CHECK (outcome IN ('success', 'not_found', 'validation_failed',
    'resource_limit')),
  occurred_at_ms INTEGER NOT NULL CHECK (occurred_at_ms >= 0)
) STRICT;
INSERT INTO statement_submission_audit_next (id, user_id, operation, outcome, occurred_at_ms)
  SELECT id, user_id, operation, outcome, occurred_at_ms FROM statement_submission_audit;
DROP TABLE statement_submission_audit;
ALTER TABLE statement_submission_audit_next RENAME TO statement_submission_audit;
CREATE INDEX statement_audit_by_user_day ON statement_submission_audit(user_id, occurred_at_ms);
CREATE TRIGGER statement_submission_audit_no_update BEFORE UPDATE ON statement_submission_audit
BEGIN SELECT RAISE(ABORT, 'audit_append_only'); END;
CREATE TRIGGER statement_submission_audit_no_delete BEFORE DELETE ON statement_submission_audit
BEGIN SELECT RAISE(ABORT, 'audit_append_only'); END;
CREATE TRIGGER statement_audit_daily_budget BEFORE INSERT ON statement_submission_audit
WHEN (SELECT COUNT(*) FROM statement_submission_audit WHERE user_id = NEW.user_id
      AND occurred_at_ms >= (NEW.occurred_at_ms / 86400000) * 86400000
      AND occurred_at_ms < ((NEW.occurred_at_ms / 86400000) + 1) * 86400000)
   + (SELECT COUNT(*) FROM transaction_audit WHERE user_id = NEW.user_id
      AND occurred_at_ms >= (NEW.occurred_at_ms / 86400000) * 86400000
      AND occurred_at_ms < ((NEW.occurred_at_ms / 86400000) + 1) * 86400000)
   + (SELECT COUNT(*) FROM pat_audit WHERE user_id = NEW.user_id
      AND ((pat_id IS NOT NULL AND operation NOT LIKE 'pats.%') OR operation = 'pats.listPATs')
      AND occurred_at_ms >= (NEW.occurred_at_ms / 86400000) * 86400000
      AND occurred_at_ms < ((NEW.occurred_at_ms / 86400000) + 1) * 86400000)
   + (SELECT COUNT(*) FROM category_audit WHERE user_id = NEW.user_id
      AND occurred_at_ms >= (NEW.occurred_at_ms / 86400000) * 86400000
      AND occurred_at_ms < ((NEW.occurred_at_ms / 86400000) + 1) * 86400000)
   + (SELECT COUNT(*) FROM memory_audit WHERE user_id = NEW.user_id
      AND occurred_at_ms >= (NEW.occurred_at_ms / 86400000) * 86400000
      AND occurred_at_ms < ((NEW.occurred_at_ms / 86400000) + 1) * 86400000) >= 256
BEGIN SELECT RAISE(ABORT, 'statement_audit_limit'); END;

-- Recreate the other four budget guards against one shared read-only count projection.
-- The PAT predicate matches 0015 exactly; PAT administration rows do not consume this budget.
CREATE VIEW canonical_audit_usage AS
  SELECT user_id, occurred_at_ms FROM statement_submission_audit
  UNION ALL SELECT user_id, occurred_at_ms FROM transaction_audit
  UNION ALL SELECT user_id, occurred_at_ms FROM pat_audit
    WHERE (pat_id IS NOT NULL AND operation NOT LIKE 'pats.%') OR operation = 'pats.listPATs'
  UNION ALL SELECT user_id, occurred_at_ms FROM category_audit
  UNION ALL SELECT user_id, occurred_at_ms FROM memory_audit;
CREATE TRIGGER transaction_audit_daily_budget BEFORE INSERT ON transaction_audit
WHEN (SELECT count(*) FROM canonical_audit_usage WHERE user_id = NEW.user_id
  AND occurred_at_ms >= (NEW.occurred_at_ms / 86400000) * 86400000
  AND occurred_at_ms < ((NEW.occurred_at_ms / 86400000) + 1) * 86400000) >= 256
BEGIN SELECT RAISE(ABORT, 'transaction_audit_limit'); END;
CREATE TRIGGER pat_canonical_daily_budget BEFORE INSERT ON pat_audit
WHEN ((NEW.pat_id IS NOT NULL AND NEW.operation NOT LIKE 'pats.%') OR NEW.operation = 'pats.listPATs')
 AND (SELECT count(*) FROM canonical_audit_usage WHERE user_id = NEW.user_id
  AND occurred_at_ms >= (NEW.occurred_at_ms / 86400000) * 86400000
  AND occurred_at_ms < ((NEW.occurred_at_ms / 86400000) + 1) * 86400000) >= 256
BEGIN SELECT RAISE(ABORT, 'transaction_audit_limit'); END;
CREATE TRIGGER category_canonical_daily_budget BEFORE INSERT ON category_audit
WHEN (SELECT count(*) FROM canonical_audit_usage WHERE user_id = NEW.user_id
  AND occurred_at_ms >= (NEW.occurred_at_ms / 86400000) * 86400000
  AND occurred_at_ms < ((NEW.occurred_at_ms / 86400000) + 1) * 86400000) >= 256
BEGIN SELECT RAISE(ABORT, 'transaction_audit_limit'); END;
CREATE TRIGGER memory_canonical_daily_budget BEFORE INSERT ON memory_audit
WHEN (SELECT count(*) FROM canonical_audit_usage WHERE user_id = NEW.user_id
  AND occurred_at_ms >= (NEW.occurred_at_ms / 86400000) * 86400000
  AND occurred_at_ms < ((NEW.occurred_at_ms / 86400000) + 1) * 86400000) >= 256
BEGIN SELECT RAISE(ABORT, 'transaction_audit_limit'); END;

CREATE TABLE forwarded_email_receipts (
  id TEXT PRIMARY KEY NOT NULL CHECK (length(id) = 36),
  user_id TEXT NOT NULL REFERENCES users(id),
  delivery_digest TEXT NOT NULL CHECK (length(delivery_digest) = 64),
  object_key TEXT NOT NULL UNIQUE,
  byte_length INTEGER NOT NULL CHECK (byte_length BETWEEN 1 AND 1048576),
  state TEXT NOT NULL CHECK (state IN ('storing', 'queued', 'expired')),
  received_at_ms INTEGER NOT NULL,
  expires_at_ms INTEGER NOT NULL CHECK (expires_at_ms > received_at_ms),
  UNIQUE (user_id, delivery_digest)
) STRICT;
CREATE INDEX forwarded_email_receipts_capacity ON forwarded_email_receipts(state, user_id, expires_at_ms);
CREATE TABLE forwarded_email_outbox (
  receipt_id TEXT PRIMARY KEY NOT NULL REFERENCES forwarded_email_receipts(id),
  user_id TEXT NOT NULL REFERENCES users(id),
  sent_at_ms INTEGER
) STRICT;
CREATE INDEX forwarded_email_outbox_pending ON forwarded_email_outbox(sent_at_ms);

-- Consent is rechecked at BOTH durable transitions, not just at the advisory envelope lookup.
CREATE TRIGGER forwarded_email_authority BEFORE INSERT ON forwarded_email_receipts
WHEN NOT EXISTS (SELECT 1 FROM onboarding_consent_records WHERE user_id = NEW.user_id)
  OR EXISTS (SELECT 1 FROM consent_user_revocations WHERE user_id = NEW.user_id)
BEGIN SELECT RAISE(ABORT, 'forwarded_email_consent'); END;
CREATE TRIGGER forwarded_email_publication_authority BEFORE UPDATE OF state ON forwarded_email_receipts
WHEN NEW.state = 'queued' AND (
  NOT EXISTS (SELECT 1 FROM onboarding_consent_records WHERE user_id = NEW.user_id)
  OR EXISTS (SELECT 1 FROM consent_user_revocations WHERE user_id = NEW.user_id))
BEGIN SELECT RAISE(ABORT, 'forwarded_email_consent'); END;

-- Enforce limits at the same serialized D1 write that reserves identity; preflight is advisory.
CREATE TRIGGER forwarded_email_capacity BEFORE INSERT ON forwarded_email_receipts
WHEN (SELECT count(*) FROM forwarded_email_receipts WHERE state IN ('storing', 'queued')
       AND expires_at_ms > NEW.received_at_ms) >= 1000
  OR (SELECT count(*) FROM forwarded_email_receipts WHERE state IN ('storing', 'queued')
       AND user_id = NEW.user_id AND expires_at_ms > NEW.received_at_ms) >= 100
BEGIN SELECT RAISE(ABORT, 'forwarded_email_capacity'); END;
