-- Category refusals need a distinct outcome so an aborted batch never records them as success.
ALTER TABLE category_audit ADD COLUMN outcome TEXT NOT NULL DEFAULT 'success'
  CHECK (outcome IN ('success', 'validation_failed'));

-- One indexed assertion per child; the operation is bound alongside the slot by the unit.
-- A CHECK constraint, not a trigger message, distinguishes an actual failed completion from an
-- unrelated trigger that happens to raise text resembling a child's marker. Successful assertions
-- reuse their bounded slots instead of accumulating per-call state.
CREATE TABLE canonical_child_guard (
  child_index INTEGER PRIMARY KEY NOT NULL CHECK (child_index BETWEEN 0 AND 11),
  operation TEXT NOT NULL,
  accepted INTEGER NOT NULL,
  budget_ok INTEGER NOT NULL DEFAULT 1,
  movement_ok INTEGER NOT NULL DEFAULT 1,
  capacity_ok INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT canonical_child_guard_0 CHECK (child_index != 0 OR accepted = 1),
  CONSTRAINT canonical_child_guard_1 CHECK (child_index != 1 OR accepted = 1),
  CONSTRAINT canonical_child_guard_2 CHECK (child_index != 2 OR accepted = 1),
  CONSTRAINT canonical_child_guard_3 CHECK (child_index != 3 OR accepted = 1),
  CONSTRAINT canonical_child_guard_4 CHECK (child_index != 4 OR accepted = 1),
  CONSTRAINT canonical_child_guard_5 CHECK (child_index != 5 OR accepted = 1),
  CONSTRAINT canonical_child_guard_6 CHECK (child_index != 6 OR accepted = 1),
  CONSTRAINT canonical_child_guard_7 CHECK (child_index != 7 OR accepted = 1),
  CONSTRAINT canonical_child_guard_8 CHECK (child_index != 8 OR accepted = 1),
  CONSTRAINT canonical_child_guard_9 CHECK (child_index != 9 OR accepted = 1),
  CONSTRAINT canonical_child_guard_10 CHECK (child_index != 10 OR accepted = 1),
  CONSTRAINT canonical_child_guard_11 CHECK (child_index != 11 OR accepted = 1),
  CONSTRAINT canonical_child_budget_0 CHECK (child_index != 0 OR budget_ok = 1),
  CONSTRAINT canonical_child_budget_1 CHECK (child_index != 1 OR budget_ok = 1),
  CONSTRAINT canonical_child_budget_2 CHECK (child_index != 2 OR budget_ok = 1),
  CONSTRAINT canonical_child_budget_3 CHECK (child_index != 3 OR budget_ok = 1),
  CONSTRAINT canonical_child_budget_4 CHECK (child_index != 4 OR budget_ok = 1),
  CONSTRAINT canonical_child_budget_5 CHECK (child_index != 5 OR budget_ok = 1),
  CONSTRAINT canonical_child_budget_6 CHECK (child_index != 6 OR budget_ok = 1),
  CONSTRAINT canonical_child_budget_7 CHECK (child_index != 7 OR budget_ok = 1),
  CONSTRAINT canonical_child_budget_8 CHECK (child_index != 8 OR budget_ok = 1),
  CONSTRAINT canonical_child_budget_9 CHECK (child_index != 9 OR budget_ok = 1),
  CONSTRAINT canonical_child_budget_10 CHECK (child_index != 10 OR budget_ok = 1),
  CONSTRAINT canonical_child_budget_11 CHECK (child_index != 11 OR budget_ok = 1),
  CONSTRAINT canonical_child_movement_0 CHECK (child_index != 0 OR movement_ok = 1),
  CONSTRAINT canonical_child_movement_1 CHECK (child_index != 1 OR movement_ok = 1),
  CONSTRAINT canonical_child_movement_2 CHECK (child_index != 2 OR movement_ok = 1),
  CONSTRAINT canonical_child_movement_3 CHECK (child_index != 3 OR movement_ok = 1),
  CONSTRAINT canonical_child_movement_4 CHECK (child_index != 4 OR movement_ok = 1),
  CONSTRAINT canonical_child_movement_5 CHECK (child_index != 5 OR movement_ok = 1),
  CONSTRAINT canonical_child_movement_6 CHECK (child_index != 6 OR movement_ok = 1),
  CONSTRAINT canonical_child_movement_7 CHECK (child_index != 7 OR movement_ok = 1),
  CONSTRAINT canonical_child_movement_8 CHECK (child_index != 8 OR movement_ok = 1),
  CONSTRAINT canonical_child_movement_9 CHECK (child_index != 9 OR movement_ok = 1),
  CONSTRAINT canonical_child_movement_10 CHECK (child_index != 10 OR movement_ok = 1),
  CONSTRAINT canonical_child_movement_11 CHECK (child_index != 11 OR movement_ok = 1),
  CONSTRAINT canonical_child_capacity_0 CHECK (child_index != 0 OR capacity_ok = 1),
  CONSTRAINT canonical_child_capacity_1 CHECK (child_index != 1 OR capacity_ok = 1),
  CONSTRAINT canonical_child_capacity_2 CHECK (child_index != 2 OR capacity_ok = 1),
  CONSTRAINT canonical_child_capacity_3 CHECK (child_index != 3 OR capacity_ok = 1),
  CONSTRAINT canonical_child_capacity_4 CHECK (child_index != 4 OR capacity_ok = 1),
  CONSTRAINT canonical_child_capacity_5 CHECK (child_index != 5 OR capacity_ok = 1),
  CONSTRAINT canonical_child_capacity_6 CHECK (child_index != 6 OR capacity_ok = 1),
  CONSTRAINT canonical_child_capacity_7 CHECK (child_index != 7 OR capacity_ok = 1),
  CONSTRAINT canonical_child_capacity_8 CHECK (child_index != 8 OR capacity_ok = 1),
  CONSTRAINT canonical_child_capacity_9 CHECK (child_index != 9 OR capacity_ok = 1),
  CONSTRAINT canonical_child_capacity_10 CHECK (child_index != 10 OR capacity_ok = 1),
  CONSTRAINT canonical_child_capacity_11 CHECK (child_index != 11 OR capacity_ok = 1)
) STRICT;
