/* Generated by tools/email-formats/generate.ts. Do not edit. */
import type { NotificationEmailFormat } from "./format-definition";
import { format as format0 } from "~/shell/ingestion/email-interpretation/formats/bbva-pse/format";
import { format as format1 } from "~/shell/ingestion/email-interpretation/formats/davibank-card/format";
import { format as format2 } from "~/shell/ingestion/email-interpretation/formats/rappicard-purchase/format";

export const generatedFormats: ReadonlyArray<NotificationEmailFormat> = [format0, format1, format2];
